### ISSUE TITLE
Casper sticky header feature is missing

### ISSUE THREAD

**Issue by styxlab** [scttcper/gatsby-theme-casper#8]
One feature I like in the original Casper theme are the sticky header bars, that dynamically fade in the article title upon scroll down a bit. Unfortunately those have vanished in this theme. It' really like to see this feature implemented here as well!

**Comment by scttcper** [comment]
I believe that’s in Casper v3 which I’m still somewhat working on

**Comment by styxlab** [comment]
Thanks for clarifying. Then I'm awaiting the v3 version. Thanks for this work!

**Comment by styxlab** [comment]
Just you know, I'm going to start experimenting with my own gatsby-ghost-casper-v3 port.
